global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "heart-disease-exporter"
    metrics_path: /metrics
    static_configs:
      - targets: ["prometheus-exporter:8000"]
        labels:
          app: "heart-disease-svc"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
